version: "3"

services:
  app:
    build:
      context: ./app/
      dockerfile: Dockerfile
    container_name: go-app
    ports:
      - "4000:8080"
    restart: always
    logging:
      driver: fluentd
      options:
        fluentd-address: host.docker.internal:24224
